name: Windows MSVC build
on:
  workflow_dispatch:
  push:
    branches:
    - dev

env:
  KF_VER: 6.8.0

jobs:
  build:
    name: build
    runs-on: windows-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        id: python
        with:
          python-version: '3.12'
      - name: Setup KDE Craft
        run: |
          # Set up directories
          mkdir ".\CraftRoot\download" | Out-Null
          mkdir ".\CraftRoot\etc" | Out-Null

          # Download Craft
          Invoke-WebRequest "https://invent.kde.org/packaging/craft/-/archive/master/craft-master.zip" -OutFile ".\CraftRoot\download\craft-master.zip"
          Expand-Archive ".\CraftRoot\download\craft-master.zip" -DestinationPath ".\CraftRoot"
          mv ".\CraftRoot\craft-master" ".\CraftRoot\craft-tmp"

          # Remove "Evil Applications" from path
          $path = ($env:PATH.Split(';') | Where-Object {($_ -ne "C:\mingw64\bin") -and ($_ -ne "C:\Program Files\Git\bin")}) -join ';'
          
          # Setup CraftSettings.ini
          $craftSettings = (Invoke-WebRequest "https://raw.githubusercontent.com/TheBill2001/craft-blueprints-qvanced/refs/heads/master/CraftSettings.Windows.MSVC.ini").Content
          $craftSettings = $craftSettings.Replace("%%PYTHON_INSTALL_DIR%%", "$env:pythonLocation")
          $craftSettings = $craftSettings.Replace("%%SHORT_PATH%%", "${{ github.workspace }}\_")
          $craftSettings = $craftSettings.Replace("%%MSYS_INSTALL_DIR%%", "C:\msys64")
          $craftSettings = $craftSettings.Replace("%%PATH%%", "$path")
          
          Set-Content -Path ".\CraftRoot\etc\CraftSettings.ini" -Value "$craftSettings"
          Set-Content -Path ".\CraftRoot\craft-tmp\etc\CraftSettings.ini" -Value "$craftSettings"
          python ".\CraftRoot\craft-tmp\bin\craft.py" craft
      - name: Build QVanced
        run: |
          python .\CraftRoot\craft\bin\craft.py --add-blueprint-repository "https://github.com/TheBill2001/craft-blueprints-qvanced.git"
          python .\CraftRoot\craft\bin\craft.py qvanced
      - name: Package QVanced
        run: |
          python .\CraftRoot\craft\bin\craft.py nsis
          python .\CraftRoot\craft\bin\craft.py --package qvanced
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: CraftRoot\tmp\*.*
